version: "3"
services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8089:8089
    volumes:
      - ..:/go/src:rw
    tty: true
    working_dir: /go/src
    #command: "/go/src/docker/build.sh"
    command: /bin/bash -c "/go/src/docker/build.sh && bash"